Repository boostcampwm-2024/web35-watchducks, pull requests merged in 2024-12, with the labels that each got.

#231 [BE] DAU 구현 방식 변경
  backend/console-server/src/log/analytics/analytics.repository.spec.ts
  backend/console-server/src/log/analytics/analytics.repository.ts
  backend/console-server/src/log/rank/rank.controller.ts
  backend/console-server/src/log/rank/rank.repository.spec.ts
  backend/console-server/src/log/rank/rank.repository.ts
Labels: task

#236 [BE] 개별 프로젝트 트래픽 요구사항 반영 (cf. 인증서 갱신 쉘 스크립트 crontab 적용)
  backend/console-server/src/log/traffic/dto/get-traffic-by-project-response.dto.ts
  backend/console-server/src/log/traffic/metric/traffic-count-by-project.metric.ts
  backend/console-server/src/log/traffic/traffic.repository.ts
  backend/console-server/src/log/traffic/traffic.service.spec.ts
  backend/console-server/src/log/traffic/traffic.service.ts
Labels: task

#234 [FE] 버그 및 코드 리팩토링
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/boundary/MainBoundary.tsx
  frontend/src/component/molecule/NavbarCustomSelect.tsx
  frontend/src/component/molecule/NavbarDefaultSelect.tsx
  frontend/src/component/molecule/NavbarMenu.tsx
  frontend/src/component/molecule/NavbarRanking.tsx
  frontend/src/component/molecule/NavbarSelect.tsx
  frontend/src/component/molecule/RankingItem.tsx
  frontend/src/component/molecule/RankingTab.tsx
  frontend/src/component/organism/NavBar.tsx
  frontend/src/component/organism/NavbarSelectWrapper.tsx
  frontend/src/component/organism/ProjectTrafficChart.tsx
  frontend/src/component/page/MainPage.tsx
  frontend/src/component/page/ProjectPage.tsx
  frontend/src/component/page/RankingPage.tsx
  frontend/src/component/template/NabvarLayout.tsx
  frontend/src/store/NavbarStore.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: task

#243 [FE] select로 프로젝트선택시 리다이렉트가 안되던 부분수정
  frontend/src/component/molecule/NavbarSelect.tsx
Labels: task

#257 [FE] 반응형 설정 추가
  frontend/src/App.tsx
  frontend/src/boundary/CustomErrorBoundary.tsx
  frontend/src/chart/PolarAreaChart.tsx
  frontend/src/component/atom/Loading.tsx
  frontend/src/component/molecule/NavbarContact.tsx
  frontend/src/component/molecule/NavbarMenu.tsx
  frontend/src/component/molecule/NavbarRanking.tsx
  frontend/src/component/molecule/NavbarSelect.tsx
  frontend/src/component/molecule/NavbarTitle.tsx
  frontend/src/component/molecule/ProjectElapsedTimeLegend.tsx
  frontend/src/component/molecule/RankingItem.tsx
  frontend/src/component/molecule/RegisterText.tsx
  frontend/src/component/molecule/ValidateTextInput.tsx
  frontend/src/component/organism/MainData.tsx
  frontend/src/component/organism/MainResponse.tsx
  frontend/src/component/organism/MainTrafficChart.tsx
  frontend/src/component/organism/NavBar.tsx
  frontend/src/component/organism/NavbarSelectWrapper.tsx
  frontend/src/component/organism/ProjectDAU.tsx
  frontend/src/component/organism/ProjectElapsedTime.tsx
  frontend/src/component/organism/ProjectSuccessRate.tsx
  frontend/src/component/organism/ProjectTrafficChart.tsx
  frontend/src/component/organism/RankingList.tsx
  frontend/src/component/organism/RegisterDescription.tsx
  frontend/src/component/organism/RegisterForm.tsx
  frontend/src/component/page/ErrorPage.tsx
  frontend/src/component/page/MainPage.tsx
  frontend/src/component/page/ProjectDetailPage.tsx
  frontend/src/component/page/RankingPage.tsx
  frontend/src/component/page/RegisterPage.tsx
  frontend/src/component/template/DataLayout.tsx
  frontend/src/component/template/MobileLayout.tsx
  frontend/src/component/template/NabvarLayout.tsx
  frontend/src/hook/useIsMobile.ts
  frontend/src/index.css
  frontend/src/store/NavbarStore.ts
  frontend/src/type/Navbar.ts
  frontend/src/type/api.ts
  frontend/tailwind.config.js
Labels: task

#258 [BE] 네임서버 Client IP 캐싱
  backend/name-server/docker-compose.yml
  backend/name-server/package-lock.json
  backend/name-server/package.json
  backend/name-server/src/app.ts
  backend/name-server/src/database/query/cache.query.interface.ts
  backend/name-server/src/database/query/cache.query.ts
  backend/name-server/src/database/redis/redis-database.ts
  backend/name-server/src/server/server.ts
  backend/name-server/src/server/utils/dns-response-builder.ts
  backend/name-server/test/database/test-cache.query.ts
  backend/name-server/test/dns-response-builder.test.ts
  backend/name-server/test/server.test.ts
Labels: feature

#270 [FE] 개별 프로젝트 페이지 화면 확대시, 소제목이 차트와 겹치던현상
  frontend/src/component/molecule/NavbarContact.tsx
  frontend/src/component/molecule/NavbarRanking.tsx
  frontend/src/component/molecule/ProjectElapsedTimeLegend.tsx
  frontend/src/component/organism/NavBar.tsx
  frontend/src/component/organism/ProjectElapsedTime.tsx
Labels: bug

#271 [FE] 화면 확대시 Response Speed에서 소제목이 겹치던 현상 수정
  frontend/src/component/molecule/NavbarContact.tsx
  frontend/src/component/molecule/NavbarRanking.tsx
  frontend/src/component/molecule/ProjectElapsedTimeLegend.tsx
  frontend/src/component/organism/NavBar.tsx
  frontend/src/component/organism/ProjectElapsedTime.tsx
Labels: bug

#276 [FE] 랭킹페이지 단위 추가, 등록페이지 설명
  frontend/asset/image/GabiaDescription.png
  frontend/src/component/molecule/NavbarMenu.tsx
  frontend/src/component/molecule/NavbarTitle.tsx
  frontend/src/component/molecule/RankingItem.tsx
  frontend/src/component/molecule/RankingTab.tsx
  frontend/src/component/molecule/RegisterText.tsx
  frontend/src/component/organism/NavBar.tsx
  frontend/src/component/organism/RankingList.tsx
  frontend/src/constant/Rank.ts
  frontend/src/type/Rank.ts
Labels: task

#281 [BE] 프록시서버 multipart/form-data 지원
  backend/proxy-server/src/server/fastify.server.ts
  backend/proxy-server/src/server/handler/proxy.handler.ts
Labels: feature

#284 [FE] 개별프로젝트페이지에서 한글 프로젝트 선택 시, 선택안되던 현상
  frontend/src/component/molecule/DarkModeButton.tsx
  frontend/src/component/molecule/NavbarCustomSelect.tsx
  frontend/src/component/molecule/NavbarTitle.tsx
  frontend/src/component/organism/NavbarSelectWrapper.tsx
  frontend/src/hook/useDarkModeAnimation.ts
Labels: bug

#285 [FE] Merge to main
  frontend/src/component/molecule/DarkModeButton.tsx
  frontend/src/component/molecule/NavbarCustomSelect.tsx
  frontend/src/component/molecule/NavbarTitle.tsx
  frontend/src/component/organism/NavbarSelectWrapper.tsx
  frontend/src/hook/useDarkModeAnimation.ts
Labels: bug

#286 [FE] 개별페이지에서 해당 서비스 리다이렉트 해주는 기능 추가
  frontend/src/component/organism/ProjectTrafficChart.tsx
  frontend/src/type/api.ts
Labels: task

#290 [FE] Merge to main
  frontend/src/boundary/CustomErrorFallback.tsx
  frontend/src/chart/README.md
  frontend/src/component/molecule/NavbarRanking.tsx
  frontend/src/component/organism/ProjectTrafficChart.tsx
  frontend/src/router/README.md
  frontend/src/store/README.md
Labels: refactor, documentation

#297 [FE] Navbar 토글시 영역이 남아있던 현상 수정
  frontend/src/component/template/NabvarLayout.tsx
Labels: bug

#299 [FE] 다크모드 관련 이미지 수정
  frontend/asset/image/FaviconLight.png
  frontend/src/component/molecule/DarkModeButton.tsx
  frontend/src/component/molecule/NavbarTitle.tsx
  frontend/src/component/organism/ProjectSuccessRate.tsx
Labels: refactor
