Repository boostcampwm-2024/web35-watchducks, pull requests merged in 2024-11, with the labels that each got.

#35 [FE] 프론트 세팅
  .github/pull_request_template.md
  front/.gitignore
  front/.prettierrc
  front/README.md
  front/eslint.config.js
  front/index.html
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/src/App.tsx
  front/src/boundary/CustomErrorBoundary.tsx
  front/src/boundary/CustomErrorFallback.tsx
  front/src/boundary/CustomQueryClient.tsx
  front/src/boundary/toastError.ts
  front/src/component/Loading.tsx
  front/src/index.css
  front/src/index.tsx
  front/src/vite-env.d.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/tsconfig.json
  front/tsconfig.node.json
  front/vite.config.ts
Labels: task

#36 [TASK] 등록페이지 폼 구현
  front/asset/image/CloudFlareDescription.png
  front/asset/image/GabiaDescription.png
  front/index.html
  front/src/App.tsx
  front/src/api/README.md
  front/src/api/post.ts
  front/src/boundary/CustomErrorBoundary.tsx
  front/src/boundary/CustomQueryClient.tsx
  front/src/boundary/README.md
  front/src/component/README.md
  front/src/component/atom/Alert.tsx
  front/src/component/atom/Button.tsx
  front/src/component/atom/H1.tsx
  front/src/component/atom/H2.tsx
  front/src/component/atom/Img.tsx
  front/src/component/atom/Input.tsx
  front/src/component/atom/Loading.tsx
  front/src/component/atom/P.tsx
  front/src/component/atom/ValidIcon.tsx
  front/src/component/molecule/NavigateButton.tsx
  front/src/component/molecule/RegisterText.tsx
  front/src/component/molecule/ValidateTextInput.tsx
  front/src/component/organism/RegisterDescription.tsx
  front/src/component/organism/RegisterForm.tsx
  front/src/component/page/MainPage.tsx
  front/src/component/page/RegisterPage.tsx
  front/src/hook/README.md
  front/src/hook/useAlert.ts
  front/src/hook/useRegisterForm.ts
  front/src/type/README.md
  front/src/type/RegisterForm.ts
  front/src/util/README.md
  front/src/util/Validate.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/tsconfig.json
  front/vite.config.ts
Labels: feature

#38 [BE] 프로젝트 등록 api 구현
  backend/console-server/.eslintrc.js
  backend/console-server/.gitignore
  backend/console-server/.prettierrc
  backend/console-server/README.md
  backend/console-server/nest-cli.json
  backend/console-server/package-lock.json
  backend/console-server/package.json
  backend/console-server/src/app.controller.spec.ts
  backend/console-server/src/app.controller.ts
  backend/console-server/src/app.module.ts
  backend/console-server/src/app.service.ts
  backend/console-server/src/config/typeorm.config.ts
  backend/console-server/src/main.ts
  backend/console-server/src/project/dto/create-project.dto.ts
  backend/console-server/src/project/entities/project.entity.ts
  backend/console-server/src/project/project.controller.spec.ts
  backend/console-server/src/project/project.controller.ts
  backend/console-server/src/project/project.module.ts
  backend/console-server/src/project/project.service.spec.ts
  backend/console-server/src/project/project.service.ts
  backend/console-server/test/app.e2e-spec.ts
  backend/console-server/test/jest-e2e.json
  backend/console-server/tsconfig.build.json
  backend/console-server/tsconfig.json
  backend/console/README.md
Labels: feature, task

#48 [FE] 릴리즈 버전업
  front/.gitignore
  front/.prettierrc
  front/README.md
  front/asset/image/CloudFlareDescription.png
  front/asset/image/GabiaDescription.png
  front/eslint.config.js
  front/index.html
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/src/App.tsx
  front/src/api/README.md
  front/src/api/post.ts
  front/src/boundary/CustomErrorBoundary.tsx
  front/src/boundary/CustomErrorFallback.tsx
  front/src/boundary/CustomQueryProvider.tsx
  front/src/boundary/README.md
  front/src/boundary/toastError.ts
  front/src/component/README.md
  front/src/component/atom/Alert.tsx
  front/src/component/atom/Button.tsx
  front/src/component/atom/H1.tsx
  front/src/component/atom/H2.tsx
  front/src/component/atom/Img.tsx
  front/src/component/atom/Input.tsx
  front/src/component/atom/Loading.tsx
  front/src/component/atom/P.tsx
  front/src/component/atom/ValidIcon.tsx
  front/src/component/molecule/NavigateButton.tsx
  front/src/component/molecule/RegisterText.tsx
  front/src/component/molecule/ValidateTextInput.tsx
  front/src/component/organism/RegisterDescription.tsx
  front/src/component/organism/RegisterForm.tsx
  front/src/component/page/MainPage.tsx
  front/src/component/page/RegisterPage.tsx
  front/src/hook/README.md
  front/src/hook/useAlert.ts
  front/src/hook/useCustomMutation.ts
  front/src/hook/useRegisterForm.ts
  front/src/index.css
  front/src/index.tsx
  front/src/type/README.md
  front/src/type/RegisterForm.ts
  front/src/util/README.md
  front/src/util/Validate.ts
  front/src/vite-env.d.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/tsconfig.json
  front/tsconfig.node.json
  front/vite.config.ts
Labels: documentation

#51 [FE] netlify설정파일 추가
  front/netlify.toml
Labels: documentation

#52 Dev front
  front/netlify.toml
Labels: documentation

#61 [BE] CI/CD 세팅 & 콘솔 서버 적용
  .github/workflows/ci-cd.yml
  .github/workflows/deploy-service.yml
  backend/console-server/.dockerignore
  backend/console-server/Dockerfile
  backend/console-server/docker-compose.yml
  backend/console-server/ecosystem.config.js
  backend/console-server/nginx.conf
  backend/console-server/src/main.ts
  backend/console-server/src/project/project.service.ts
Labels: feature

#60 [BE] 기수별 프로젝트 리스트 응답 API 구현
  backend/console-server/src/config/typeorm.config.ts
  backend/console-server/src/project/dto/find-by-generation-response.dto.ts
  backend/console-server/src/project/dto/find-by-generation.dto.ts
  backend/console-server/src/project/entities/project.entity.ts
  backend/console-server/src/project/project.controller.ts
  backend/console-server/src/project/project.service.spec.ts
  backend/console-server/src/project/project.service.ts
Labels: feature, task

#64 [BE] 데이터베이스 연동 및 테스트 쿼리 작성
  backend/console-server/docker-compose.yml
  backend/console-server/src/app.module.ts
  backend/console-server/src/clickhouse/clickhouse.config.ts
  backend/console-server/src/clickhouse/clickhouse.ts
  backend/console-server/src/config/clickhouse.config.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.module.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.ts
Labels: feature, task

#66 [FE] 메인페이지 관련 레이아웃 추가
  front/.gitignore
  front/asset/image/ProjectActive.png
  front/asset/image/ProjectInactive.png
  front/asset/image/ProjectsActive.png
  front/asset/image/ProjectsInactive.png
  front/asset/image/RankingActive.png
  front/asset/image/RankingInactive.png
  front/src/App.tsx
  front/src/boundary/toastError.ts
  front/src/component/atom/Img.tsx
  front/src/component/molecule/NavigateButton.tsx
  front/src/component/molecule/RegisterText.tsx
  front/src/component/organism/RegisterDescription.tsx
  front/src/component/organism/RegisterForm.tsx
  front/src/component/page/MainPage.tsx
  front/src/component/page/ProjectPage.tsx
  front/src/component/page/RankingPage.tsx
  front/src/component/page/RegisterPage.tsx
  front/src/component/template/MainPageLayout.tsx
  front/src/component/template/NavbarLayout.tsx
  front/src/hook/useRegisterForm.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/tsconfig.json
  front/vite.config.ts
Labels: feature, refactor

#65 [BE] 프록시 서버 테스트 케이스 작성
  backend/proxy-server/package-lock.json
  backend/proxy-server/package.json
  backend/proxy-server/test/common/logger/fastify.logger.test.ts
  backend/proxy-server/test/domain/log/http-log-entity.test.ts
  backend/proxy-server/test/domain/log/log.repository.test.ts
  backend/proxy-server/test/domain/log/log.service.test.ts
  backend/proxy-server/test/integration.test.ts
  backend/proxy-server/test/server/utils.test.ts
Labels: task

#70 [BE] Swagger API 명세 UI 연동 및 구현
  backend/console-server/package-lock.json
  backend/console-server/package.json
  backend/console-server/src/clickhouse/clickhouse.ts
  backend/console-server/src/clickhouse/query-builder/time-series.query-builder.ts
  backend/console-server/src/clickhouse/util/date-range.ts
  backend/console-server/src/clickhouse/util/metric-expressions.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.ts
  backend/console-server/src/main.ts
  backend/console-server/src/project/dto/create-project-response.dto.ts
  backend/console-server/src/project/dto/create-project.dto.ts
  backend/console-server/src/project/dto/find-by-generation-response.dto.ts
  backend/console-server/src/project/dto/find-by-generation.dto.ts
  backend/console-server/src/project/project.controller.ts
  backend/console-server/src/project/project.service.ts
Labels: feature, task

#68 [FE] Navbar컴포넌트 일부완성
  front/src/api/get.ts
  front/src/api/post.ts
  front/src/boundary/CustomErrorBoundary.tsx
  front/src/boundary/CustomErrorFallback.tsx
  front/src/boundary/CustomQueryProvider.tsx
  front/src/component/atom/Loading.tsx
  front/src/component/atom/Select.tsx
  front/src/component/molecule/NavbarMenu.tsx
  front/src/component/molecule/NavbarMenuItem.tsx
  front/src/component/molecule/NavbarSelect.tsx
  front/src/component/molecule/NavbarTitle.tsx
  front/src/component/molecule/NavigateButton.tsx
  front/src/component/organism/NavBar.tsx
  front/src/component/organism/NavbarSelectWrapper.tsx
  front/src/component/organism/RegisterDescription.tsx
  front/src/constant/NavbarMenu.ts
  front/src/constant/NavbarSelect.ts
  front/src/hook/useGroup.ts
  front/src/type/Navbar.ts
Labels: feature

#94 [FE] 메인페이지 구현
  front/asset/image/Favicon.png
  front/asset/image/FirstMedal.png
  front/asset/image/SecondMedal.png
  front/asset/image/ThirdMedal.png
  front/index.html
  front/package-lock.json
  front/package.json
  front/src/api/get.ts
  front/src/boundary/CustomErrorBoundary.tsx
  front/src/boundary/CustomErrorFallback.tsx
  front/src/component/atom/Loading.tsx
  front/src/component/atom/Select.tsx
  front/src/component/atom/Span.tsx
  front/src/component/molecule/NavbarCustomSelect.tsx
  front/src/component/molecule/NavbarDefaultSelect.tsx
  front/src/component/molecule/NavbarMenu.tsx
  front/src/component/molecule/NavbarRanking.tsx
  front/src/component/molecule/NavbarSelect.tsx
  front/src/component/organism/NavBar.tsx
  front/src/component/organism/NavbarSelectWrapper.tsx
  front/src/component/organism/RegisterForm.tsx
  front/src/component/page/MainPage.tsx
  front/src/constant/Medals.ts
  front/src/constant/NavbarSelect.ts
  front/src/hook/useGroup.ts
  front/src/hook/useGroupNames.ts
  front/src/hook/useRankings.ts
  front/src/hook/useRegisterForm.ts
  front/src/hook/useTotalDatas.ts
  front/src/type/Navbar.ts
  front/src/type/RegisterForm.ts
  front/src/util/Validate.ts
  front/tailwind.config.js
Labels: feature

#107 [BE] 개별 프로젝트 경로별 응답 소요 시간 api 테스트 코드 작성
  backend/console-server/src/clickhouse/query-builder/time-series.query-builder.ts
  backend/console-server/src/clickhouse/util/map-filter-condition.ts
  backend/console-server/src/clickhouse/util/metric-expressions.ts
  backend/console-server/src/log/dto/get-path-speed-rank-response.dto.ts
  backend/console-server/src/log/log.contorller.spec.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.repository.spec.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.spec.ts
Labels: task

#116 [BE] DAU 테이블 생성 및 NameServer에서 값 갱신
  backend/console-server/src/clickhouse/clickhouse.ts
  backend/name-server/package-lock.json
  backend/name-server/package.json
  backend/name-server/src/app.ts
  backend/name-server/src/database/clickhouse/clickhouse-database.ts
  backend/name-server/src/database/clickhouse/config/clickhouse.config.ts
  backend/name-server/src/database/query/dau-recorder.ts
  backend/name-server/src/database/query/project.query.ts
  backend/name-server/src/server/server.ts
  backend/name-server/src/server/utils/dns-response-builder.ts
Labels: feature, task

#117 [BE] 개별 프로젝트 날짜별 DAU(일일 활성 사용자) API 구현
  backend/console-server/src/log/dto/get-dau-by-project-response.dto.ts
  backend/console-server/src/log/dto/get-dau-by-project.dto.ts
  backend/console-server/src/log/log.contorller.spec.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.repository.spec.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.spec.ts
  backend/console-server/src/log/log.service.ts
  backend/name-server/src/server/server.ts
Labels: feature, task

#118 [BE] 전체 프로젝트 전일 대비 트래픽 증가량 기능 구현
  backend/console-server/src/log/dto/get-traffic-daily-difference-response.dto.ts
  backend/console-server/src/log/dto/get-traffic-daily-difference.dto.ts
  backend/console-server/src/log/log.contorller.spec.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.repository.spec.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.spec.ts
  backend/console-server/src/log/log.service.ts
Labels: feature, task

#134 [BE] 트래픽 TOP5 프로젝트에 대한 라인 차트 데이터 쿼리 API
  backend/console-server/src/app.controller.spec.ts
  backend/console-server/src/log/dto/get-avg-elapsed-time.dto.ts
  backend/console-server/src/log/dto/get-traffic-daily-difference-response.dto.ts
  backend/console-server/src/log/dto/get-traffic-rank.dto.ts
  backend/console-server/src/log/dto/get-traffic-top5-chart-response.dto.ts
  backend/console-server/src/log/dto/get-traffic-top5-chart.dto.ts
  backend/console-server/src/log/log.contorller.spec.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.ts
  backend/console-server/src/log/metric/traffic-rank-top5.metric.ts
  backend/console-server/src/log/metric/trafficChart.metric.ts
  backend/console-server/test/app.e2e-spec.ts
Labels: feature

#136 [BE] TOP5 응답 속도 API
  backend/console-server/src/log/dto/get-speed-rank-response.dto.ts
  backend/console-server/src/log/dto/get-speed-rank.dto.ts
  backend/console-server/src/log/log.contorller.spec.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/log.repository.spec.ts
  backend/console-server/src/log/log.repository.ts
  backend/console-server/src/log/log.service.spec.ts
  backend/console-server/src/log/log.service.ts
  backend/console-server/src/log/metric/speed-rank.metric.ts
Labels: feature, task

#133 [FE] 메인페이지 응답속도 차트 구현
  front/asset/image/Favicon.svg
  front/asset/image/ProjectsActive.png
  front/asset/image/ProjectsActive.svg
  front/asset/image/ProjectsInactive.svg
  front/index.html
  front/package-lock.json
  front/package.json
  front/src/api/get.ts
  front/src/boundary/CustomErrorFallback.tsx
  front/src/chart/BarChart.tsx
  front/src/chart/Chart.tsx
  front/src/chart/LineChart.tsx
  front/src/component/atom/Loading.tsx
  front/src/component/molecule/DarkModeButton.tsx
  front/src/component/molecule/NavbarContact.tsx
  front/src/component/molecule/NavbarMenu.tsx
  front/src/component/molecule/NavbarRanking.tsx
  front/src/component/molecule/NavbarSelect.tsx
  front/src/component/molecule/NavbarTitle.tsx
  front/src/component/organism/MainData.tsx
  front/src/component/organism/MainResponse.tsx
  front/src/component/organism/MainTrafficChart.tsx
  front/src/component/organism/NavBar.tsx
  front/src/component/organism/NavbarSelectWrapper.tsx
  front/src/component/organism/RegisterDescription.tsx
  front/src/component/organism/RegisterForm.tsx
  front/src/component/page/MainPage.tsx
  front/src/component/page/RegisterPage.tsx
  front/src/component/template/DataLayout.tsx
  front/src/constant/Medals.ts
  front/src/constant/NavbarMenu.ts
  front/src/hook/api/useRankings.ts
  front/src/hook/api/useTop5ResponseTime.ts
  front/src/hook/api/useTotalDatas.ts
  front/src/hook/useDarkMode.ts
  front/src/hook/useDarkModeAnimation.ts
  front/src/hook/useDefaultOption.ts
  front/src/type/Navbar.ts
  front/src/type/api.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/tsconfig.json
  front/vite.config.ts
Labels: task

#146 [FE] 메인페이지 트래픽 차트 데이터적용
  front/src/api/get.ts
  front/src/chart/LineChart.tsx
  front/src/component/organism/MainTrafficChart.tsx
  front/src/component/page/MainPage.tsx
  front/src/hook/api/useTop5Traffic.ts
  front/src/hook/useDefaultOption.ts
  front/src/type/api.ts
Labels: feature

#149 [BE] 코드 수정에 따른 미통과 테스트케이스 수정
  backend/console-server/src/clickhouse/util/date-range.ts
  backend/console-server/src/log/log.contorller.spec.ts
  backend/console-server/src/log/log.repository.spec.ts
  backend/console-server/src/log/log.service.spec.ts
  backend/console-server/src/log/log.service.ts
  backend/console-server/src/project/project.service.spec.ts
Labels: bug

#154 [BE] 작은 리팩토링, Redis 캐싱 도입
  backend/console-server/docker-compose.yml
  backend/console-server/package-lock.json
  backend/console-server/package.json
  backend/console-server/src/app.module.ts
  backend/console-server/src/app.service.ts
  backend/console-server/src/config/redis.config.ts
  backend/console-server/src/log/analytics/analytics.controller.spec.ts
  backend/console-server/src/log/analytics/analytics.controller.ts
  backend/console-server/src/log/analytics/analytics.module.ts
  backend/console-server/src/log/analytics/analytics.repository.spec.ts
  backend/console-server/src/log/analytics/analytics.repository.ts
  backend/console-server/src/log/analytics/analytics.service.spec.ts
  backend/console-server/src/log/analytics/analytics.service.ts
  backend/console-server/src/log/analytics/dto/get-project-dau-response.dto.ts
  backend/console-server/src/log/analytics/dto/get-project-dau.dto.ts
  backend/console-server/src/log/analytics/metric/dau.metric.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.controller.spec.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.controller.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.service.ts
  backend/console-server/src/log/log.module.ts
  backend/console-server/src/log/success-rate/success-rate.controller.spec.ts
  backend/console-server/src/log/success-rate/success-rate.controller.ts
  backend/console-server/src/log/traffic/dto/get-traffic-daily-difference-response.dto.ts
  backend/console-server/src/log/traffic/traffic.service.ts
Labels: feature, task

#162 [BE] log 도메인의 API 엔드포인트에 누락된 prefix 추가
  backend/console-server/src/log/analytics/analytics.controller.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.controller.ts
  backend/console-server/src/log/log.controller.ts
  backend/console-server/src/log/success-rate/success-rate.controller.ts
  backend/console-server/src/log/traffic/traffic.controller.ts
Labels: bug

#168 [FE] 메인페이지 구현하기
  front/src/chart/BarChart.tsx
  front/src/chart/Chart.tsx
  front/src/chart/LineChart.tsx
  front/src/component/organism/MainData.tsx
  front/src/component/organism/MainResponse.tsx
  front/src/component/organism/MainTrafficChart.tsx
  front/src/component/page/MainPage.tsx
  front/src/constant/ChartColors.ts
  front/src/constant/Time.ts
  front/src/hook/useDefaultOption.ts
  front/src/util/Time.ts
Labels: task

#171 [BE] 기수내 응답 성공률 랭킹 API 구현
  backend/console-server/src/log/log.module.ts
  backend/console-server/src/log/rank/dto/get-success-rate-rank-response.dto.ts
  backend/console-server/src/log/rank/dto/get-success-rate-rank.dto.ts
  backend/console-server/src/log/rank/metric/host-error-rate.metric.ts
  backend/console-server/src/log/rank/rank.controller.spec.ts
  backend/console-server/src/log/rank/rank.controller.ts
  backend/console-server/src/log/rank/rank.module.ts
  backend/console-server/src/log/rank/rank.repository.spec.ts
  backend/console-server/src/log/rank/rank.repository.ts
  backend/console-server/src/log/rank/rank.service.spec.ts
  backend/console-server/src/log/rank/rank.service.ts
  backend/console-server/src/log/traffic/traffic.repository.ts
Labels: feature

#169 [BE] "NS"타입 DNS Query에 응답 & 작은 리팩토링 (createFlag)
  backend/name-server/Dockerfile
  backend/name-server/docker-compose.yml
  backend/name-server/src/common/utils/validator/configuration.validator.ts
  backend/name-server/src/database/query/dau-recorder.ts
  backend/name-server/src/server/constant/dns-packet.constant.ts
  backend/name-server/src/server/server.ts
  backend/name-server/src/server/utils/dns-response-builder.ts
  backend/name-server/src/server/utils/packet.validator.ts
  backend/name-server/test/dns-response-builder.test.ts
  backend/name-server/test/server.test.ts
Labels: feature, refactor

#172 [BE] 개별 프로젝트 트래픽 API에 변경된 요구사항 반영해 수정
  backend/console-server/Dockerfile
  backend/console-server/docker-compose.yml
  backend/console-server/src/log/traffic/dto/get-traffic-by-project-response.dto.ts
  backend/console-server/src/log/traffic/dto/get-traffic-by-project.dto.ts
  backend/console-server/src/log/traffic/traffic.constant.ts
  backend/console-server/src/log/traffic/traffic.controller.spec.ts
  backend/console-server/src/log/traffic/traffic.controller.ts
  backend/console-server/src/log/traffic/traffic.repository.spec.ts
  backend/console-server/src/log/traffic/traffic.repository.ts
  backend/console-server/src/log/traffic/traffic.service.spec.ts
  backend/console-server/src/log/traffic/traffic.service.ts
Labels: feature

#176 [BE] 개별 프로젝트 DAU 수정 요구사항 반영
  backend/console-server/src/clickhouse/query-builder/time-series.query-builder.ts
  backend/console-server/src/log/analytics/analytics.controller.spec.ts
  backend/console-server/src/log/analytics/analytics.controller.ts
  backend/console-server/src/log/analytics/analytics.repository.spec.ts
  backend/console-server/src/log/analytics/analytics.repository.ts
  backend/console-server/src/log/analytics/analytics.service.spec.ts
  backend/console-server/src/log/analytics/analytics.service.ts
  backend/console-server/src/log/analytics/dto/get-project-dau-response.dto.ts
  backend/console-server/src/log/analytics/dto/get-project-dau.dto.ts
  backend/console-server/src/log/analytics/metric/dau.metric.ts
  backend/console-server/src/log/rank/rank.controller.spec.ts
  backend/name-server/src/database/query/dau-recorder.ts
Labels: feature

#173 [BE] Proxy Server 리팩토링
  backend/proxy-server/jest.config.js
  backend/proxy-server/package.json
  backend/proxy-server/src/app.ts
  backend/proxy-server/src/common/constant/error-message.constant.ts
  backend/proxy-server/src/common/constant/http-status.constant.ts
  backend/proxy-server/src/common/error/create-system.error.ts
  backend/proxy-server/src/common/error/database-query.error.ts
  backend/proxy-server/src/common/error/domain-not-found.error.ts
  backend/proxy-server/src/common/error/factories/application-error.factory.ts
  backend/proxy-server/src/common/error/factories/system-error.factory.ts
  backend/proxy-server/src/common/error/missing-host-header.error.ts
  backend/proxy-server/src/common/error/types/application-error.type.ts
  backend/proxy-server/src/common/error/types/system-error.type.ts
  backend/proxy-server/src/common/utils/date.util.ts
  backend/proxy-server/src/database/query/log.repository.clickhouse.ts
  backend/proxy-server/src/domain/log/log.handler.ts
  backend/proxy-server/src/domain/log/log.service.ts
  backend/proxy-server/src/domain/proxy/proxy.handler.ts
  backend/proxy-server/src/domain/proxy/proxy.service.ts
  backend/proxy-server/src/index.ts
  backend/proxy-server/src/server/config/server.configuration.ts
  backend/proxy-server/src/server/config/server.initializer.ts
  backend/proxy-server/src/server/server.ts
  backend/proxy-server/test/domain/log/log.service.test.ts
  backend/proxy-server/test/integration.test.ts
  backend/proxy-server/tsconfig.test.json
Labels: refactor

#182 [BE] 랭킹 페이지 DAU API 구현
  backend/console-server/src/log/rank/dto/get-dau-rank-response.dto.ts
  backend/console-server/src/log/rank/dto/get-dau-rank.dto.ts
  backend/console-server/src/log/rank/metric/host-dau.metric.ts
  backend/console-server/src/log/rank/rank.controller.spec.ts
  backend/console-server/src/log/rank/rank.controller.ts
  backend/console-server/src/log/rank/rank.repository.spec.ts
  backend/console-server/src/log/rank/rank.repository.ts
  backend/console-server/src/log/rank/rank.service.spec.ts
  backend/console-server/src/log/rank/rank.service.ts
Labels: feature

#184 [BE] 랭킹 페이지 응답 시간 기준 랭킹 API 구현
  backend/console-server/src/log/elapsed-time/elapsed-time.controller.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.repository.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.service.ts
  backend/console-server/src/log/rank/dto/get-elapsed-time-rank-response.dto.ts
  backend/console-server/src/log/rank/dto/get-elapsed-time-rank.dto.ts
  backend/console-server/src/log/rank/metric/host-elapsed-time.metric.ts
  backend/console-server/src/log/rank/rank.controller.spec.ts
  backend/console-server/src/log/rank/rank.controller.ts
  backend/console-server/src/log/rank/rank.repository.spec.ts
  backend/console-server/src/log/rank/rank.repository.ts
  backend/console-server/src/log/rank/rank.service.spec.ts
  backend/console-server/src/log/rank/rank.service.ts
  backend/console-server/src/log/traffic/traffic.repository.spec.ts
Labels: feature

#186 [BE] 트래픽 TOP5 프로젝트의 작일 트래픽 차트 데이터 API 테스트 케이스 작성
  backend/console-server/src/log/traffic/traffic.controller.spec.ts
  backend/console-server/src/log/traffic/traffic.service.spec.ts
  backend/console-server/src/log/traffic/traffic.service.ts
  backend/console-server/src/project/project.service.ts
Labels: test

#189 [FE] 개별 프로젝트페이지 일부완성, 에러페이지 완성
  front/eslint.config.js
  front/src/App.tsx
  front/src/api/axios.ts
  front/src/api/get.ts
  front/src/boundary/CustomQueryProvider.tsx
  front/src/boundary/MainBoundary.tsx
  front/src/chart/BarChart.tsx
  front/src/chart/LineChart.tsx
  front/src/chart/PieChart.tsx
  front/src/chart/PolarAreaChart.tsx
  front/src/component/atom/Span.tsx
  front/src/component/molecule/NavbarCustomSelect.tsx
  front/src/component/molecule/NavbarMenu.tsx
  front/src/component/molecule/NavbarRanking.tsx
  front/src/component/molecule/NavbarSelect.tsx
  front/src/component/molecule/ProjectElapsedTimeLegend.tsx
  front/src/component/organism/MainResponse.tsx
  front/src/component/organism/MainTrafficChart.tsx
  front/src/component/organism/NavbarSelectWrapper.tsx
  front/src/component/organism/ProjectDAU.tsx
  front/src/component/organism/ProjectElapsedTime.tsx
  front/src/component/organism/ProjectSuccessRate.tsx
  front/src/component/page/ErrorPage.tsx
  front/src/component/page/MainPage.tsx
  front/src/component/page/ProjectDetailPage.tsx
  front/src/component/page/ProjectPage.tsx
  front/src/constant/Chart.ts
  front/src/constant/ChartColors.ts
  front/src/hook/api/useGroupNames.ts
  front/src/hook/api/useIsExistGroup.ts
  front/src/hook/api/useProjectDAU.ts
  front/src/hook/api/useProjectElapsedTime.ts
  front/src/hook/api/useProjectSuccessRate.ts
  front/src/hook/api/useRankings.ts
  front/src/hook/api/useTop5ResponseTime.ts
  front/src/hook/api/useTop5Traffic.ts
  front/src/hook/api/useTotalDatas.ts
  front/src/type/api.ts
  front/src/util/Time.ts
Labels: task

#192 [FE] 배포관련 에러 수정
  frontend/src/component/organism/ProjectDAU.tsx
  frontend/src/index.tsx
Labels: task

#195 [BE] 프록시 서버 요청 Host에 대한 ip 캐싱 구현
  backend/proxy-server/docker-compose.yml
  backend/proxy-server/package-lock.json
  backend/proxy-server/package.json
  backend/proxy-server/src/app.ts
  backend/proxy-server/src/database/mysql/mysql-database.ts
  backend/proxy-server/src/database/query/project-cache.repository.redis.ts
  backend/proxy-server/src/database/redis/redis-database.ts
  backend/proxy-server/src/domain/project/project-cache.repository.ts
  backend/proxy-server/src/domain/project/project.service.ts
  backend/proxy-server/src/domain/proxy/proxy.service.ts
  backend/proxy-server/src/index.ts
  backend/proxy-server/src/server/config/fastify.config.ts
  backend/proxy-server/src/server/server.ts
  backend/proxy-server/src/server/utils.ts
Labels: feature

#198 [FE] 개별프로젝트 페이지 완성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/get.ts
  frontend/src/chart/LineChart.tsx
  frontend/src/chart/PieChart.tsx
  frontend/src/chart/PolarAreaChart.tsx
  frontend/src/component/organism/MainTrafficChart.tsx
  frontend/src/component/organism/ProjectDAU.tsx
  frontend/src/component/organism/ProjectElapsedTime.tsx
  frontend/src/component/organism/ProjectSuccessRate.tsx
  frontend/src/component/organism/ProjectTrafficChart.tsx
  frontend/src/component/page/ProjectDetailPage.tsx
  frontend/src/constant/Date.ts
  frontend/src/hook/api/useProjectTraffic.ts
  frontend/src/index.tsx
  frontend/src/type/Date.ts
  frontend/src/type/api.ts
Labels: task

#197 [BE] 커스텀 Cache Interceptor 구현 및 적용
  backend/console-server/src/common/cache/cache.constant.ts
  backend/console-server/src/common/cache/cache.decorator.ts
  backend/console-server/src/common/cache/cache.interceptor.ts
  backend/console-server/src/common/cache/index.ts
  backend/console-server/src/log/elapsed-time/elapsed-time.controller.ts
  backend/console-server/src/log/rank/rank.controller.spec.ts
  backend/console-server/src/log/rank/rank.controller.ts
  backend/console-server/src/log/success-rate/success-rate.controller.ts
  backend/console-server/src/log/traffic/traffic.controller.spec.ts
  backend/console-server/src/log/traffic/traffic.controller.ts
  backend/console-server/src/project/project.controller.spec.ts
  backend/console-server/src/project/project.controller.ts
Labels: feature

#202 [FE] 개별프로젝트 페이지 짜잘한 수정
  frontend/src/component/molecule/NavbarRanking.tsx
  frontend/src/component/organism/MainTrafficChart.tsx
  frontend/src/index.css
Labels: task
